sudo: required
services:
  - docker
before_install:
  - docker build -t laxtour/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run laxtour/react-test npm run test -- --coverage

after_success:
  - docker build -t laxtour/multi-client ./client
  - docker build -t laxtour/multi-nginx ./nginx
  - docker build -t laxtour/multi-server ./server
  - docker build -t laxtour/multi-worker ./worker
  #Login into docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take those images and push them to docker hub
  - docker push laxtour/multi-client 
  - docker push laxtour/multi-nginx
  - docker push laxtour/multi-server
  - docker push laxtour/multi-worker

deploy:
  provider: elasticbeanstalk
  region: us-east-1
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-1-417481896964
  bucket_path: docket-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY 