name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
    - run: docker build -t laxtour/multi-client ./client
    - run: docker build -t laxtour/multi-nginx ./nginx
    - run: docker build -t laxtour/multi-server ./server
    - run: docker build -t laxtour/multi-worker ./worker
