name: Docker Image CI

on:
  push:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        docker build -t laxtour/multi-client ./client
        docker build -t laxtour/multi-nginx ./nginx
        docker build -t laxtour/multi-server ./server
        docker build -t laxtour/multi-worker ./worker
        
        
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
       username: ${{ secrets.DOCKER_USERNAME }}
       password: ${{ secrets.DOCKER_PASSWORD }}
       repository: msusdev/webnext
       tags: latest, ${{ github.run_number }}
